baseURL: 'https://rolf.golf/'
languageCode: en-us
title: RaR
theme: PaperMod

params:
    defaultTheme: light
    profileMode:
        enabled: true
        title: "Hey ich bin Aaron &#128075;"
        subtitle: "Personal blog, maybe portfolio laaaater"
        imageUrl: "/Blog_Cover.png" # optional
        imageTitle: "Beautiful Blog Cover" # optional
        imageWidth: 240 # custom size
        imageHeight: 240 # custom size
        buttons:
            -   name: Archive
                url: "/archive"
            -   name: Github
                url: "https://github.com/AaronLeontaris"
        

    socialIcons: # optional
        -   name: "twitter"
            url: "https://twitter.com/RonaldTrettmann"
        -   name: "github"
            url: "https://github.com/AaronLeontaris"
    
    hugoEncryptorLanguage : "en-us"   

    hugoLeaflet:
    css:
      - href: "https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
        params:
          integrity: "sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
        crossorigin: ""
      - href: "https://unpkg.com/@raruto/leaflet-elevation@1.1.1/dist/leaflet-elevation.css"
      - href: "css/leaflet.extra-markers.min.css"
    js:
      - src: "https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
        params:
          integrity: "sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
        crossorigin: ""
      - src: "js/leaflet.elevation.js"
      - src: "js/leaflet.hugo.js"
      - src: "js/leaflet.extra-markers.min.js"

menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: by tag
      url: /tags/
      weight: 20
    - identifier: languages
      name: by language
      url: /languages/
      weight: 30

taxonomies:
  tag: tags
  language: languages

markup:
  goldmark:
    renderer:
      unsafe: true

# outputs:
#    home:
#        - HTML
#        - RSS
#        - JSON # is necessary